import type { StarterPack } from "./types";

/**
 * Pack de waterpolo: primer deporte soportado.
 * Sólo se registran métricas primarias; todo indicador porcentual o de
 * eficacia es derivado y se calcula con fórmulas declarativas.
 */
export const waterpoloPack: StarterPack = {
  id: "waterpolo_base",
  name: "Waterpolo — Rendimiento base",
  summary:
    "Catálogo inicial de waterpolo: ataque, defensa, portería, disciplina y participación, con métricas derivadas de eficacia y un perfil de valoración general.",
  version: "1.0.0",
  author: "Nevermine Platform",
  publishedAt: "2026-01-01",
  status: "published",
  origin: "official",
  compatibility: { engine: "sportspace", minEngineVersion: "1.0.0" },
  sport: { code: "waterpolo", name: "Waterpolo" },
  // FEATURE-003.9 — Canal oficial y actualización anunciada, nunca silenciosa.
  distribution: { channel: "stable", updatePolicy: "notify" },

  catalog: {
    code: "waterpolo_base",
    name: "Waterpolo — Rendimiento base",
    description:
      "Catálogo de partida para equipos de waterpolo. Puedes añadir, desactivar o repesar métricas sin tocar código.",
  },
  groups: [
    { code: "ataque", name: "Ataque", color: "#2563eb", icon: "Target" },
    { code: "defensa", name: "Defensa", color: "#0f766e", icon: "Shield" },
    { code: "porteria", name: "Portería", color: "#7c3aed", icon: "Hand" },
    { code: "disciplina", name: "Disciplina", color: "#dc2626", icon: "AlertTriangle" },
    { code: "participacion", name: "Participación", color: "#64748b", icon: "Clock" },
  ],
  metrics: [
    // Ataque (primarias)
    {
      code: "goles",
      name: "Goles",
      group: "ataque",
      nature: "primary",
      valueType: "counter",
      direction: "higher_is_better",
      scope: "individual",
      shortDescription: "Goles anotados.",
    },
    {
      code: "tiros",
      name: "Tiros",
      group: "ataque",
      nature: "primary",
      valueType: "counter",
      direction: "neutral",
      scope: "individual",
      shortDescription: "Tiros totales realizados.",
    },
    {
      code: "asistencias",
      name: "Asistencias",
      group: "ataque",
      nature: "primary",
      valueType: "counter",
      direction: "higher_is_better",
      scope: "individual",
    },
    {
      code: "penaltis_lanzados",
      name: "Penaltis lanzados",
      group: "ataque",
      nature: "primary",
      valueType: "counter",
      direction: "neutral",
      scope: "individual",
    },
    {
      code: "penaltis_anotados",
      name: "Penaltis anotados",
      group: "ataque",
      nature: "primary",
      valueType: "counter",
      direction: "higher_is_better",
      scope: "individual",
    },
    {
      code: "perdidas",
      name: "Pérdidas de balón",
      group: "ataque",
      nature: "primary",
      valueType: "counter",
      direction: "lower_is_better",
      scope: "individual",
    },
    {
      code: "superioridades_jugadas",
      name: "Superioridades jugadas",
      group: "ataque",
      nature: "primary",
      valueType: "counter",
      direction: "neutral",
      scope: "collective",
    },
    {
      code: "superioridades_anotadas",
      name: "Superioridades anotadas",
      group: "ataque",
      nature: "primary",
      valueType: "counter",
      direction: "higher_is_better",
      scope: "collective",
    },

    // Defensa (primarias)
    {
      code: "robos",
      name: "Robos",
      group: "defensa",
      nature: "primary",
      valueType: "counter",
      direction: "higher_is_better",
      scope: "individual",
    },
    {
      code: "bloqueos",
      name: "Bloqueos",
      group: "defensa",
      nature: "primary",
      valueType: "counter",
      direction: "higher_is_better",
      scope: "individual",
    },
    {
      code: "expulsiones_provocadas",
      name: "Expulsiones provocadas",
      group: "defensa",
      nature: "primary",
      valueType: "counter",
      direction: "higher_is_better",
      scope: "individual",
    },

    // Portería (primarias)
    {
      code: "paradas",
      name: "Paradas",
      group: "porteria",
      nature: "primary",
      valueType: "counter",
      direction: "higher_is_better",
      scope: "individual",
    },
    {
      code: "goles_encajados",
      name: "Goles encajados",
      group: "porteria",
      nature: "primary",
      valueType: "counter",
      direction: "lower_is_better",
      scope: "individual",
    },
    {
      code: "penaltis_parados",
      name: "Penaltis parados",
      group: "porteria",
      nature: "primary",
      valueType: "counter",
      direction: "higher_is_better",
      scope: "individual",
    },

    // Disciplina (primarias)
    {
      code: "expulsiones_cometidas",
      name: "Expulsiones cometidas",
      group: "disciplina",
      nature: "primary",
      valueType: "counter",
      direction: "lower_is_better",
      scope: "individual",
    },
    {
      code: "penaltis_cometidos",
      name: "Penaltis cometidos",
      group: "disciplina",
      nature: "primary",
      valueType: "counter",
      direction: "lower_is_better",
      scope: "individual",
    },

    // Participación (primarias)
    {
      code: "minutos_jugados",
      name: "Minutos jugados",
      group: "participacion",
      nature: "primary",
      valueType: "duration",
      direction: "neutral",
      scope: "individual",
      unit: "min",
    },
    {
      code: "titular",
      name: "Titular",
      group: "participacion",
      nature: "primary",
      valueType: "boolean",
      direction: "neutral",
      scope: "individual",
    },

    // Derivadas
    {
      code: "eficacia_tiro",
      name: "Eficacia de tiro",
      group: "ataque",
      nature: "derived",
      valueType: "ratio",
      direction: "higher_is_better",
      scope: "individual",
      unit: "%",
      shortDescription: "Goles sobre tiros totales.",
      formula: "safe_div(goles, tiros, 0) * 100",
    },
    {
      code: "eficacia_penalti",
      name: "Eficacia de penalti",
      group: "ataque",
      nature: "derived",
      valueType: "ratio",
      direction: "higher_is_better",
      scope: "individual",
      unit: "%",
      formula: "safe_div(penaltis_anotados, penaltis_lanzados, 0) * 100",
    },
    {
      code: "eficacia_superioridad",
      name: "Eficacia en superioridad",
      group: "ataque",
      nature: "derived",
      valueType: "ratio",
      direction: "higher_is_better",
      scope: "collective",
      unit: "%",
      formula: "safe_div(superioridades_anotadas, superioridades_jugadas, 0) * 100",
    },
    {
      code: "porcentaje_parada",
      name: "Porcentaje de parada",
      group: "porteria",
      nature: "derived",
      valueType: "ratio",
      direction: "higher_is_better",
      scope: "individual",
      unit: "%",
      formula: "safe_div(paradas, paradas + goles_encajados, 0) * 100",
    },
    {
      code: "acciones_positivas",
      name: "Acciones positivas",
      group: "defensa",
      nature: "derived",
      valueType: "counter",
      direction: "higher_is_better",
      scope: "individual",
      formula: "robos + bloqueos + expulsiones_provocadas",
    },
    {
      code: "balance_disciplina",
      name: "Balance disciplinario",
      group: "disciplina",
      nature: "derived",
      valueType: "counter",
      direction: "lower_is_better",
      scope: "individual",
      formula: "expulsiones_cometidas + penaltis_cometidos",
    },
  ],
  profiles: [
    {
      code: "rendimiento_general",
      name: "Rendimiento general",
      description:
        "Perfil de partida: pondera aportación ofensiva, trabajo defensivo y pérdida de disciplina.",
      weights: [
        { metric: "goles", weight: 4, sign: 1 },
        { metric: "asistencias", weight: 3, sign: 1 },
        { metric: "eficacia_tiro", weight: 0.5, sign: 1 },
        { metric: "acciones_positivas", weight: 2, sign: 1 },
        { metric: "porcentaje_parada", weight: 0.5, sign: 1 },
        { metric: "perdidas", weight: 2, sign: -1 },
        { metric: "balance_disciplina", weight: 1.5, sign: -1 },
      ],
    },
  ],
};
